// Code generated by "stringer -output=stringer.UserStatus.go -type=UserStatus -trimprefix=UserStatus"; DO NOT EDIT.

package dom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserStatusFreeze-1]
	_ = x[UserStatusDefault-2]
	_ = x[UserStatusPremium-3]
	_ = x[UserStatusSupport-4]
	_ = x[UserStatusAdmin-5]
	_ = x[UserStatusJedi-6]
}

const _UserStatus_name = "FreezeDefaultPremiumSupportAdminJedi"

var _UserStatus_index = [...]uint8{0, 6, 13, 20, 27, 32, 36}

func (i UserStatus) String() string {
	i -= 1
	if i >= UserStatus(len(_UserStatus_index)-1) {
		return "UserStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UserStatus_name[_UserStatus_index[i]:_UserStatus_index[i+1]]
}
