// Code generated by "stringer -output=stringer.SolutionStatus.go -type=SolutionStatus -trimprefix=SolutionStatus"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SolutionStatusNew-1]
	_ = x[SolutionStatusApprove-2]
	_ = x[SolutionStatusCancel-3]
}

const _SolutionStatus_name = "NewApproveCancel"

var _SolutionStatus_index = [...]uint8{0, 3, 10, 16}

func (i SolutionStatus) String() string {
	i -= 1
	if i >= SolutionStatus(len(_SolutionStatus_index)-1) {
		return "SolutionStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SolutionStatus_name[_SolutionStatus_index[i]:_SolutionStatus_index[i+1]]
}
