// Code generated by "stringer -output=stringer.TaskKind.go -type=TaskKind -trimprefix=TaskKind"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TaskKindEventAdd-1]
	_ = x[TaskKindEventDel-2]
	_ = x[TaskKindEventUpdate-3]
}

const _TaskKind_name = "EventAddEventDelEventUpdate"

var _TaskKind_index = [...]uint8{0, 8, 16, 27}

func (i TaskKind) String() string {
	i -= 1
	if i >= TaskKind(len(_TaskKind_index)-1) {
		return "TaskKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TaskKind_name[_TaskKind_index[i]:_TaskKind_index[i+1]]
}
