// Code generated by "stringer -output=stringer.FileFormat.go -type=FileFormat -trimprefix=FileFormat"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileFormatWebp-1]
	_ = x[FileFormatPng-2]
	_ = x[FileFormatJpeg-3]
	_ = x[FileFormatGif-4]
	_ = x[FileFormatRaw-5]
	_ = x[FileFormatSvg-6]
}

const _FileFormat_name = "WebpPngJpegGifRawSvg"

var _FileFormat_index = [...]uint8{0, 4, 7, 11, 14, 17, 20}

func (i FileFormat) String() string {
	i -= 1
	if i >= FileFormat(len(_FileFormat_index)-1) {
		return "FileFormat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FileFormat_name[_FileFormat_index[i]:_FileFormat_index[i+1]]
}
