// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/annotations/v1/annotations.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	code "google.golang.org/genproto/googleapis/rpc/code"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = code.Code(0)
)

// Validate checks the field values on MethodRule with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MethodRule) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MethodRule with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MethodRuleMultiError, or
// nil if none found.
func (m *MethodRule) ValidateAll() error {
	return m.validate(true)
}

func (m *MethodRule) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NeedAuthorization

	if len(errors) > 0 {
		return MethodRuleMultiError(errors)
	}

	return nil
}

// MethodRuleMultiError is an error wrapping multiple validation errors
// returned by MethodRule.ValidateAll() if the designated constraints aren't met.
type MethodRuleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MethodRuleMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MethodRuleMultiError) AllErrors() []error { return m }

// MethodRuleValidationError is the validation error returned by
// MethodRule.Validate if the designated constraints aren't met.
type MethodRuleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MethodRuleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MethodRuleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MethodRuleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MethodRuleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MethodRuleValidationError) ErrorName() string { return "MethodRuleValidationError" }

// Error satisfies the builtin error interface
func (e MethodRuleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMethodRule.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MethodRuleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MethodRuleValidationError{}

// Validate checks the field values on ServiceRule with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ServiceRule) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServiceRule with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ServiceRuleMultiError, or
// nil if none found.
func (m *ServiceRule) ValidateAll() error {
	return m.validate(true)
}

func (m *ServiceRule) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ServiceRuleMultiError(errors)
	}

	return nil
}

// ServiceRuleMultiError is an error wrapping multiple validation errors
// returned by ServiceRule.ValidateAll() if the designated constraints aren't met.
type ServiceRuleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServiceRuleMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServiceRuleMultiError) AllErrors() []error { return m }

// ServiceRuleValidationError is the validation error returned by
// ServiceRule.Validate if the designated constraints aren't met.
type ServiceRuleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceRuleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceRuleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceRuleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceRuleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceRuleValidationError) ErrorName() string { return "ServiceRuleValidationError" }

// Error satisfies the builtin error interface
func (e ServiceRuleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceRule.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceRuleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceRuleValidationError{}
