// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/user_status/v1/user_status.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind of user`s status.
type StatusKind int32

const (
	// For unknown value.
	// Can't be anyway.
	StatusKind_STATUS_KIND_NONE StatusKind = 0
	// Kind of user who was banned.
	StatusKind_STATUS_KIND_FREEZE StatusKind = 1
	// Kind hat is assigned to all users at registration.
	StatusKind_STATUS_KIND_DEFAULT StatusKind = 2
	// Kind of premium user.
	StatusKind_STATUS_KIND_PREMIUM StatusKind = 3
	// Kind of user support.
	StatusKind_STATUS_KIND_SUPPORT StatusKind = 4
	// Kind of user admin.
	StatusKind_STATUS_KIND_ADMIN StatusKind = 5
	// Kind of super user.
	StatusKind_STATUS_KIND_JEDI StatusKind = 6
)

// Enum value maps for StatusKind.
var (
	StatusKind_name = map[int32]string{
		0: "STATUS_KIND_NONE",
		1: "STATUS_KIND_FREEZE",
		2: "STATUS_KIND_DEFAULT",
		3: "STATUS_KIND_PREMIUM",
		4: "STATUS_KIND_SUPPORT",
		5: "STATUS_KIND_ADMIN",
		6: "STATUS_KIND_JEDI",
	}
	StatusKind_value = map[string]int32{
		"STATUS_KIND_NONE":    0,
		"STATUS_KIND_FREEZE":  1,
		"STATUS_KIND_DEFAULT": 2,
		"STATUS_KIND_PREMIUM": 3,
		"STATUS_KIND_SUPPORT": 4,
		"STATUS_KIND_ADMIN":   5,
		"STATUS_KIND_JEDI":    6,
	}
)

func (x StatusKind) Enum() *StatusKind {
	p := new(StatusKind)
	*p = x
	return p
}

func (x StatusKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_user_status_v1_user_status_proto_enumTypes[0].Descriptor()
}

func (StatusKind) Type() protoreflect.EnumType {
	return &file_api_user_status_v1_user_status_proto_enumTypes[0]
}

func (x StatusKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusKind.Descriptor instead.
func (StatusKind) EnumDescriptor() ([]byte, []int) {
	return file_api_user_status_v1_user_status_proto_rawDescGZIP(), []int{0}
}

var File_api_user_status_v1_user_status_proto protoreflect.FileDescriptor

var file_api_user_status_v1_user_status_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x2a, 0xb2, 0x01, 0x0a, 0x0a, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x46,
	0x52, 0x45, 0x45, 0x5a, 0x45, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x02,
	0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x50, 0x52, 0x45, 0x4d, 0x49, 0x55, 0x4d, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54,
	0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x4a, 0x45, 0x44, 0x49, 0x10, 0x06, 0x42,
	0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x5a, 0x65,
	0x72, 0x67, 0x73, 0x4c, 0x61, 0x77, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x2d, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_user_status_v1_user_status_proto_rawDescOnce sync.Once
	file_api_user_status_v1_user_status_proto_rawDescData = file_api_user_status_v1_user_status_proto_rawDesc
)

func file_api_user_status_v1_user_status_proto_rawDescGZIP() []byte {
	file_api_user_status_v1_user_status_proto_rawDescOnce.Do(func() {
		file_api_user_status_v1_user_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_user_status_v1_user_status_proto_rawDescData)
	})
	return file_api_user_status_v1_user_status_proto_rawDescData
}

var file_api_user_status_v1_user_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_user_status_v1_user_status_proto_goTypes = []interface{}{
	(StatusKind)(0), // 0: api.user_status.v1.StatusKind
}
var file_api_user_status_v1_user_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_user_status_v1_user_status_proto_init() }
func file_api_user_status_v1_user_status_proto_init() {
	if File_api_user_status_v1_user_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_user_status_v1_user_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_user_status_v1_user_status_proto_goTypes,
		DependencyIndexes: file_api_user_status_v1_user_status_proto_depIdxs,
		EnumInfos:         file_api_user_status_v1_user_status_proto_enumTypes,
	}.Build()
	File_api_user_status_v1_user_status_proto = out.File
	file_api_user_status_v1_user_status_proto_rawDesc = nil
	file_api_user_status_v1_user_status_proto_goTypes = nil
	file_api_user_status_v1_user_status_proto_depIdxs = nil
}
